### ISSUE TITLE
Where is the ‘rlkit/config/launcher_config_template.py ’

### ISSUE THREAD

**Issue by SatireY** [chongyi-zheng/stable_contrastive_rl#1]
I want to run your program locally, but I don't know much about the meaning of the items in 'rlkit/launchers/config_template.py', and I haven't found the 'rlkit/config/launcher_config_template.py '' example you provided in the repository. Did you forget to push up？

**Comment by chongyi-zheng** [comment]
Thanks for reporting this! That file was just `config_template.py` under `rlkit/launchers`. I have updated the README. My code was adapted from [rlkit](https://github.com/rail-berkeley/rlkit). That config file doesn't prevent you from running the experiments.
