### ISSUE TITLE
Questions about the data set.

### ISSUE THREAD

**Issue by SatireY** [chongyi-zheng/stable_contrastive_rl#2]
Thanks for your reply to the previous question, now the experiment can be run in my local, but I still have a question, is the training data env6_td_pnp_push_dataset a multi-task dataset? It is also a dataset for a single task (one of drawer, pick and place, pushblock open(close) drawer). Looking forward to your reply!

**Comment by chongyi-zheng** [comment]
It's a dataset containing multiple primitive behaviors, you can check Appendix D in the paper for a description.
